POST http://localhost:5000/auth/generaluser/test
Content-Type: application/json     
Authorization: bearer 

{
    "tokenId": "this is token id hum"
}

###
POST http://localhost:5000/auth/generaluser/erase
Content-Type: application/json     

