GET http://localhost:5000/ngo/donation/our-donation/0/1000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjE0OWFkOTI2ZTliMGM3ZWY5OTA0NDlhIiwicm9sZSI6Im5nbyIsImlhdCI6MTYzMjIxODUzNywiZXhwIjoxNjMyMzA0OTM3fQ.TI1fNipazPDshLKe0aWBjHzlEWY2nSL0rKaX-krw8OQ 7f2b813bf27cad4f028a7d41b8920e6a21e4b5cee95932d1f87b995a5a228df08635f796a6326b8f7524f7bc1deda632bca9529c44707f7b55f5403492af3468
Content-Type: application/json

###
PATCH http://localhost:5000/ngo/donation/accept-donation
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjE0OWFkOTI2ZTliMGM3ZWY5OTA0NDlhIiwicm9sZSI6Im5nbyIsImlhdCI6MTYzMjIxODUzNywiZXhwIjoxNjMyMzA0OTM3fQ.TI1fNipazPDshLKe0aWBjHzlEWY2nSL0rKaX-krw8OQ
Content-Type: application/json

{
    "donationId":"614860ef664831a1a4b693bb"
}

###
PATCH http://localhost:5000/ngo/donation/received-donation
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjE0OWFkOTI2ZTliMGM3ZWY5OTA0NDlhIiwicm9sZSI6Im5nbyIsImlhdCI6MTYzMjIxODUzNywiZXhwIjoxNjMyMzA0OTM3fQ.TI1fNipazPDshLKe0aWBjHzlEWY2nSL0rKaX-krw8OQ
Content-Type: application/json

{
    "donationId":"614860ef664831a1a4b693bb"
}